sudo: false

branches:
  only:
    - development

addons:
  apt:
    packages:
      - doxygen

script:
  - cd study
  - doxygen Doxyfile

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: study/html
    github-token: $GITHUB_TOKEN
    on:
      branch: development