@startuml
scale 1.5
class EuropeanOption {
    + void init()
    + void copy(const EuropeanOption& o2)
    + double CallPrice() const
    + double PutPrice() const
    + double CallDelta() const;
	+ double PutDelta() const;
	+ double CallGamma() const;
	+ double PutGamma() const;
	+ double CallVega() const;
	+ double PutVega() const;
    + double n(double x) const;
	+ double N(double x) const;
    + double r
	+ double sig
	+ double K
	+ double T
	+ double U
	+ double b
    + std::string optType
    + std::string unam
    + EuropeanOption()
	+ EuropeanOption(const EuropeanOption& option2)
	+ EuropeanOption (const std::string& optionType)
    ~ virtual ~EuropeanOption()
    + EuropeanOption& operator = (const EuropeanOption& option2)
    + double Price() const
	+ double Delta() const
	+ void toggle()
}

@enduml